// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package org.multibit.contact;

public final class MBHDProtos {
  private MBHDProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TagOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string tag_value = 1;
    boolean hasTagValue();
    String getTagValue();
  }
  public static final class Tag extends
      com.google.protobuf.GeneratedMessage
      implements TagOrBuilder {
    // Use Tag.newBuilder() to construct.
    private Tag(Builder builder) {
      super(builder);
    }
    private Tag(boolean noInit) {}
    
    private static final Tag defaultInstance;
    public static Tag getDefaultInstance() {
      return defaultInstance;
    }
    
    public Tag getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.multibit.contact.MBHDProtos.internal_static_wallet_Tag_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.multibit.contact.MBHDProtos.internal_static_wallet_Tag_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string tag_value = 1;
    public static final int TAG_VALUE_FIELD_NUMBER = 1;
    private java.lang.Object tagValue_;
    public boolean hasTagValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTagValue() {
      java.lang.Object ref = tagValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tagValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTagValueBytes() {
      java.lang.Object ref = tagValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tagValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      tagValue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTagValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTagValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTagValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.multibit.contact.MBHDProtos.Tag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Tag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.multibit.contact.MBHDProtos.Tag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.multibit.contact.MBHDProtos.TagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.multibit.contact.MBHDProtos.internal_static_wallet_Tag_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.multibit.contact.MBHDProtos.internal_static_wallet_Tag_fieldAccessorTable;
      }
      
      // Construct using org.multibit.contact.MBHDProtos.Tag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        tagValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.multibit.contact.MBHDProtos.Tag.getDescriptor();
      }
      
      public org.multibit.contact.MBHDProtos.Tag getDefaultInstanceForType() {
        return org.multibit.contact.MBHDProtos.Tag.getDefaultInstance();
      }
      
      public org.multibit.contact.MBHDProtos.Tag build() {
        org.multibit.contact.MBHDProtos.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.multibit.contact.MBHDProtos.Tag buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.multibit.contact.MBHDProtos.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.multibit.contact.MBHDProtos.Tag buildPartial() {
        org.multibit.contact.MBHDProtos.Tag result = new org.multibit.contact.MBHDProtos.Tag(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tagValue_ = tagValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.multibit.contact.MBHDProtos.Tag) {
          return mergeFrom((org.multibit.contact.MBHDProtos.Tag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.multibit.contact.MBHDProtos.Tag other) {
        if (other == org.multibit.contact.MBHDProtos.Tag.getDefaultInstance()) return this;
        if (other.hasTagValue()) {
          setTagValue(other.getTagValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTagValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tagValue_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string tag_value = 1;
      private java.lang.Object tagValue_ = "";
      public boolean hasTagValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTagValue() {
        java.lang.Object ref = tagValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tagValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTagValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tagValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearTagValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tagValue_ = getDefaultInstance().getTagValue();
        onChanged();
        return this;
      }
      void setTagValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        tagValue_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:wallet.Tag)
    }
    
    static {
      defaultInstance = new Tag(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wallet.Tag)
  }
  
  public interface ContactOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // optional string email = 3;
    boolean hasEmail();
    String getEmail();
    
    // optional string image_path = 4;
    boolean hasImagePath();
    String getImagePath();
    
    // optional string bitcoin_address = 5;
    boolean hasBitcoinAddress();
    String getBitcoinAddress();
    
    // optional string extended_public_key = 6;
    boolean hasExtendedPublicKey();
    String getExtendedPublicKey();
    
    // optional string notes = 7;
    boolean hasNotes();
    String getNotes();
    
    // repeated .wallet.Tag tag = 8;
    java.util.List<org.multibit.contact.MBHDProtos.Tag> 
        getTagList();
    org.multibit.contact.MBHDProtos.Tag getTag(int index);
    int getTagCount();
    java.util.List<? extends org.multibit.contact.MBHDProtos.TagOrBuilder> 
        getTagOrBuilderList();
    org.multibit.contact.MBHDProtos.TagOrBuilder getTagOrBuilder(
        int index);
    
    // optional uint32 star_style = 9;
    boolean hasStarStyle();
    int getStarStyle();
  }
  public static final class Contact extends
      com.google.protobuf.GeneratedMessage
      implements ContactOrBuilder {
    // Use Contact.newBuilder() to construct.
    private Contact(Builder builder) {
      super(builder);
    }
    private Contact(boolean noInit) {}
    
    private static final Contact defaultInstance;
    public static Contact getDefaultInstance() {
      return defaultInstance;
    }
    
    public Contact getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.multibit.contact.MBHDProtos.internal_static_wallet_Contact_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.multibit.contact.MBHDProtos.internal_static_wallet_Contact_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string image_path = 4;
    public static final int IMAGE_PATH_FIELD_NUMBER = 4;
    private java.lang.Object imagePath_;
    public boolean hasImagePath() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImagePath() {
      java.lang.Object ref = imagePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imagePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImagePathBytes() {
      java.lang.Object ref = imagePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string bitcoin_address = 5;
    public static final int BITCOIN_ADDRESS_FIELD_NUMBER = 5;
    private java.lang.Object bitcoinAddress_;
    public boolean hasBitcoinAddress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getBitcoinAddress() {
      java.lang.Object ref = bitcoinAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bitcoinAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBitcoinAddressBytes() {
      java.lang.Object ref = bitcoinAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bitcoinAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string extended_public_key = 6;
    public static final int EXTENDED_PUBLIC_KEY_FIELD_NUMBER = 6;
    private java.lang.Object extendedPublicKey_;
    public boolean hasExtendedPublicKey() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getExtendedPublicKey() {
      java.lang.Object ref = extendedPublicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          extendedPublicKey_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExtendedPublicKeyBytes() {
      java.lang.Object ref = extendedPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        extendedPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string notes = 7;
    public static final int NOTES_FIELD_NUMBER = 7;
    private java.lang.Object notes_;
    public boolean hasNotes() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          notes_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .wallet.Tag tag = 8;
    public static final int TAG_FIELD_NUMBER = 8;
    private java.util.List<org.multibit.contact.MBHDProtos.Tag> tag_;
    public java.util.List<org.multibit.contact.MBHDProtos.Tag> getTagList() {
      return tag_;
    }
    public java.util.List<? extends org.multibit.contact.MBHDProtos.TagOrBuilder> 
        getTagOrBuilderList() {
      return tag_;
    }
    public int getTagCount() {
      return tag_.size();
    }
    public org.multibit.contact.MBHDProtos.Tag getTag(int index) {
      return tag_.get(index);
    }
    public org.multibit.contact.MBHDProtos.TagOrBuilder getTagOrBuilder(
        int index) {
      return tag_.get(index);
    }
    
    // optional uint32 star_style = 9;
    public static final int STAR_STYLE_FIELD_NUMBER = 9;
    private int starStyle_;
    public boolean hasStarStyle() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getStarStyle() {
      return starStyle_;
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
      email_ = "";
      imagePath_ = "";
      bitcoinAddress_ = "";
      extendedPublicKey_ = "";
      notes_ = "";
      tag_ = java.util.Collections.emptyList();
      starStyle_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTagCount(); i++) {
        if (!getTag(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImagePathBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBitcoinAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getExtendedPublicKeyBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getNotesBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(8, tag_.get(i));
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(9, starStyle_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImagePathBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBitcoinAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getExtendedPublicKeyBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getNotesBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, tag_.get(i));
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, starStyle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.multibit.contact.MBHDProtos.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.multibit.contact.MBHDProtos.Contact prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.multibit.contact.MBHDProtos.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.multibit.contact.MBHDProtos.internal_static_wallet_Contact_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.multibit.contact.MBHDProtos.internal_static_wallet_Contact_fieldAccessorTable;
      }
      
      // Construct using org.multibit.contact.MBHDProtos.Contact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        imagePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        bitcoinAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        extendedPublicKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        notes_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          tagBuilder_.clear();
        }
        starStyle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.multibit.contact.MBHDProtos.Contact.getDescriptor();
      }
      
      public org.multibit.contact.MBHDProtos.Contact getDefaultInstanceForType() {
        return org.multibit.contact.MBHDProtos.Contact.getDefaultInstance();
      }
      
      public org.multibit.contact.MBHDProtos.Contact build() {
        org.multibit.contact.MBHDProtos.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.multibit.contact.MBHDProtos.Contact buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.multibit.contact.MBHDProtos.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.multibit.contact.MBHDProtos.Contact buildPartial() {
        org.multibit.contact.MBHDProtos.Contact result = new org.multibit.contact.MBHDProtos.Contact(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.imagePath_ = imagePath_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bitcoinAddress_ = bitcoinAddress_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.extendedPublicKey_ = extendedPublicKey_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.notes_ = notes_;
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.starStyle_ = starStyle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.multibit.contact.MBHDProtos.Contact) {
          return mergeFrom((org.multibit.contact.MBHDProtos.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.multibit.contact.MBHDProtos.Contact other) {
        if (other == org.multibit.contact.MBHDProtos.Contact.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasImagePath()) {
          setImagePath(other.getImagePath());
        }
        if (other.hasBitcoinAddress()) {
          setBitcoinAddress(other.getBitcoinAddress());
        }
        if (other.hasExtendedPublicKey()) {
          setExtendedPublicKey(other.getExtendedPublicKey());
        }
        if (other.hasNotes()) {
          setNotes(other.getNotes());
        }
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000080);
              tagBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        if (other.hasStarStyle()) {
          setStarStyle(other.getStarStyle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getTagCount(); i++) {
          if (!getTag(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              imagePath_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              bitcoinAddress_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              extendedPublicKey_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              notes_ = input.readBytes();
              break;
            }
            case 66: {
              org.multibit.contact.MBHDProtos.Tag.Builder subBuilder = org.multibit.contact.MBHDProtos.Tag.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTag(subBuilder.buildPartial());
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              starStyle_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string email = 3;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
      }
      
      // optional string image_path = 4;
      private java.lang.Object imagePath_ = "";
      public boolean hasImagePath() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImagePath() {
        java.lang.Object ref = imagePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imagePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImagePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imagePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearImagePath() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imagePath_ = getDefaultInstance().getImagePath();
        onChanged();
        return this;
      }
      void setImagePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        imagePath_ = value;
        onChanged();
      }
      
      // optional string bitcoin_address = 5;
      private java.lang.Object bitcoinAddress_ = "";
      public boolean hasBitcoinAddress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getBitcoinAddress() {
        java.lang.Object ref = bitcoinAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bitcoinAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBitcoinAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bitcoinAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearBitcoinAddress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bitcoinAddress_ = getDefaultInstance().getBitcoinAddress();
        onChanged();
        return this;
      }
      void setBitcoinAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        bitcoinAddress_ = value;
        onChanged();
      }
      
      // optional string extended_public_key = 6;
      private java.lang.Object extendedPublicKey_ = "";
      public boolean hasExtendedPublicKey() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getExtendedPublicKey() {
        java.lang.Object ref = extendedPublicKey_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          extendedPublicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExtendedPublicKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        extendedPublicKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearExtendedPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        extendedPublicKey_ = getDefaultInstance().getExtendedPublicKey();
        onChanged();
        return this;
      }
      void setExtendedPublicKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        extendedPublicKey_ = value;
        onChanged();
      }
      
      // optional string notes = 7;
      private java.lang.Object notes_ = "";
      public boolean hasNotes() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNotes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        notes_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      void setNotes(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        notes_ = value;
        onChanged();
      }
      
      // repeated .wallet.Tag tag = 8;
      private java.util.List<org.multibit.contact.MBHDProtos.Tag> tag_ =
        java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          tag_ = new java.util.ArrayList<org.multibit.contact.MBHDProtos.Tag>(tag_);
          bitField0_ |= 0x00000080;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.multibit.contact.MBHDProtos.Tag, org.multibit.contact.MBHDProtos.Tag.Builder, org.multibit.contact.MBHDProtos.TagOrBuilder> tagBuilder_;
      
      public java.util.List<org.multibit.contact.MBHDProtos.Tag> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      public org.multibit.contact.MBHDProtos.Tag getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      public Builder setTag(
          int index, org.multibit.contact.MBHDProtos.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTag(
          int index, org.multibit.contact.MBHDProtos.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTag(org.multibit.contact.MBHDProtos.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTag(
          int index, org.multibit.contact.MBHDProtos.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTag(
          org.multibit.contact.MBHDProtos.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTag(
          int index, org.multibit.contact.MBHDProtos.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTag(
          java.lang.Iterable<? extends org.multibit.contact.MBHDProtos.Tag> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          super.addAll(values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      public org.multibit.contact.MBHDProtos.Tag.Builder getTagBuilder(
          int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      public org.multibit.contact.MBHDProtos.TagOrBuilder getTagOrBuilder(
          int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.multibit.contact.MBHDProtos.TagOrBuilder> 
           getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      public org.multibit.contact.MBHDProtos.Tag.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
            org.multibit.contact.MBHDProtos.Tag.getDefaultInstance());
      }
      public org.multibit.contact.MBHDProtos.Tag.Builder addTagBuilder(
          int index) {
        return getTagFieldBuilder().addBuilder(
            index, org.multibit.contact.MBHDProtos.Tag.getDefaultInstance());
      }
      public java.util.List<org.multibit.contact.MBHDProtos.Tag.Builder> 
           getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.multibit.contact.MBHDProtos.Tag, org.multibit.contact.MBHDProtos.Tag.Builder, org.multibit.contact.MBHDProtos.TagOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.multibit.contact.MBHDProtos.Tag, org.multibit.contact.MBHDProtos.Tag.Builder, org.multibit.contact.MBHDProtos.TagOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }
      
      // optional uint32 star_style = 9;
      private int starStyle_ ;
      public boolean hasStarStyle() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getStarStyle() {
        return starStyle_;
      }
      public Builder setStarStyle(int value) {
        bitField0_ |= 0x00000100;
        starStyle_ = value;
        onChanged();
        return this;
      }
      public Builder clearStarStyle() {
        bitField0_ = (bitField0_ & ~0x00000100);
        starStyle_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:wallet.Contact)
    }
    
    static {
      defaultInstance = new Contact(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wallet.Contact)
  }
  
  public interface ContactsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .wallet.Contact id = 1;
    java.util.List<org.multibit.contact.MBHDProtos.Contact> 
        getIdList();
    org.multibit.contact.MBHDProtos.Contact getId(int index);
    int getIdCount();
    java.util.List<? extends org.multibit.contact.MBHDProtos.ContactOrBuilder> 
        getIdOrBuilderList();
    org.multibit.contact.MBHDProtos.ContactOrBuilder getIdOrBuilder(
        int index);
  }
  public static final class Contacts extends
      com.google.protobuf.GeneratedMessage
      implements ContactsOrBuilder {
    // Use Contacts.newBuilder() to construct.
    private Contacts(Builder builder) {
      super(builder);
    }
    private Contacts(boolean noInit) {}
    
    private static final Contacts defaultInstance;
    public static Contacts getDefaultInstance() {
      return defaultInstance;
    }
    
    public Contacts getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.multibit.contact.MBHDProtos.internal_static_wallet_Contacts_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.multibit.contact.MBHDProtos.internal_static_wallet_Contacts_fieldAccessorTable;
    }
    
    // repeated .wallet.Contact id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<org.multibit.contact.MBHDProtos.Contact> id_;
    public java.util.List<org.multibit.contact.MBHDProtos.Contact> getIdList() {
      return id_;
    }
    public java.util.List<? extends org.multibit.contact.MBHDProtos.ContactOrBuilder> 
        getIdOrBuilderList() {
      return id_;
    }
    public int getIdCount() {
      return id_.size();
    }
    public org.multibit.contact.MBHDProtos.Contact getId(int index) {
      return id_.get(index);
    }
    public org.multibit.contact.MBHDProtos.ContactOrBuilder getIdOrBuilder(
        int index) {
      return id_.get(index);
    }
    
    private void initFields() {
      id_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getIdCount(); i++) {
        if (!getId(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < id_.size(); i++) {
        output.writeMessage(1, id_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < id_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, id_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.multibit.contact.MBHDProtos.Contacts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.multibit.contact.MBHDProtos.Contacts prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.multibit.contact.MBHDProtos.ContactsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.multibit.contact.MBHDProtos.internal_static_wallet_Contacts_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.multibit.contact.MBHDProtos.internal_static_wallet_Contacts_fieldAccessorTable;
      }
      
      // Construct using org.multibit.contact.MBHDProtos.Contacts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          idBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.multibit.contact.MBHDProtos.Contacts.getDescriptor();
      }
      
      public org.multibit.contact.MBHDProtos.Contacts getDefaultInstanceForType() {
        return org.multibit.contact.MBHDProtos.Contacts.getDefaultInstance();
      }
      
      public org.multibit.contact.MBHDProtos.Contacts build() {
        org.multibit.contact.MBHDProtos.Contacts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.multibit.contact.MBHDProtos.Contacts buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.multibit.contact.MBHDProtos.Contacts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.multibit.contact.MBHDProtos.Contacts buildPartial() {
        org.multibit.contact.MBHDProtos.Contacts result = new org.multibit.contact.MBHDProtos.Contacts(this);
        int from_bitField0_ = bitField0_;
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            id_ = java.util.Collections.unmodifiableList(id_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.multibit.contact.MBHDProtos.Contacts) {
          return mergeFrom((org.multibit.contact.MBHDProtos.Contacts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.multibit.contact.MBHDProtos.Contacts other) {
        if (other == org.multibit.contact.MBHDProtos.Contacts.getDefaultInstance()) return this;
        if (idBuilder_ == null) {
          if (!other.id_.isEmpty()) {
            if (id_.isEmpty()) {
              id_ = other.id_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIdIsMutable();
              id_.addAll(other.id_);
            }
            onChanged();
          }
        } else {
          if (!other.id_.isEmpty()) {
            if (idBuilder_.isEmpty()) {
              idBuilder_.dispose();
              idBuilder_ = null;
              id_ = other.id_;
              bitField0_ = (bitField0_ & ~0x00000001);
              idBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIdFieldBuilder() : null;
            } else {
              idBuilder_.addAllMessages(other.id_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getIdCount(); i++) {
          if (!getId(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.multibit.contact.MBHDProtos.Contact.Builder subBuilder = org.multibit.contact.MBHDProtos.Contact.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addId(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .wallet.Contact id = 1;
      private java.util.List<org.multibit.contact.MBHDProtos.Contact> id_ =
        java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<org.multibit.contact.MBHDProtos.Contact>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.multibit.contact.MBHDProtos.Contact, org.multibit.contact.MBHDProtos.Contact.Builder, org.multibit.contact.MBHDProtos.ContactOrBuilder> idBuilder_;
      
      public java.util.List<org.multibit.contact.MBHDProtos.Contact> getIdList() {
        if (idBuilder_ == null) {
          return java.util.Collections.unmodifiableList(id_);
        } else {
          return idBuilder_.getMessageList();
        }
      }
      public int getIdCount() {
        if (idBuilder_ == null) {
          return id_.size();
        } else {
          return idBuilder_.getCount();
        }
      }
      public org.multibit.contact.MBHDProtos.Contact getId(int index) {
        if (idBuilder_ == null) {
          return id_.get(index);
        } else {
          return idBuilder_.getMessage(index);
        }
      }
      public Builder setId(
          int index, org.multibit.contact.MBHDProtos.Contact value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdIsMutable();
          id_.set(index, value);
          onChanged();
        } else {
          idBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setId(
          int index, org.multibit.contact.MBHDProtos.Contact.Builder builderForValue) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.set(index, builderForValue.build());
          onChanged();
        } else {
          idBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addId(org.multibit.contact.MBHDProtos.Contact value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdIsMutable();
          id_.add(value);
          onChanged();
        } else {
          idBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addId(
          int index, org.multibit.contact.MBHDProtos.Contact value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdIsMutable();
          id_.add(index, value);
          onChanged();
        } else {
          idBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addId(
          org.multibit.contact.MBHDProtos.Contact.Builder builderForValue) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.add(builderForValue.build());
          onChanged();
        } else {
          idBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addId(
          int index, org.multibit.contact.MBHDProtos.Contact.Builder builderForValue) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.add(index, builderForValue.build());
          onChanged();
        } else {
          idBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllId(
          java.lang.Iterable<? extends org.multibit.contact.MBHDProtos.Contact> values) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          super.addAll(values, id_);
          onChanged();
        } else {
          idBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          idBuilder_.clear();
        }
        return this;
      }
      public Builder removeId(int index) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.remove(index);
          onChanged();
        } else {
          idBuilder_.remove(index);
        }
        return this;
      }
      public org.multibit.contact.MBHDProtos.Contact.Builder getIdBuilder(
          int index) {
        return getIdFieldBuilder().getBuilder(index);
      }
      public org.multibit.contact.MBHDProtos.ContactOrBuilder getIdOrBuilder(
          int index) {
        if (idBuilder_ == null) {
          return id_.get(index);  } else {
          return idBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.multibit.contact.MBHDProtos.ContactOrBuilder> 
           getIdOrBuilderList() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(id_);
        }
      }
      public org.multibit.contact.MBHDProtos.Contact.Builder addIdBuilder() {
        return getIdFieldBuilder().addBuilder(
            org.multibit.contact.MBHDProtos.Contact.getDefaultInstance());
      }
      public org.multibit.contact.MBHDProtos.Contact.Builder addIdBuilder(
          int index) {
        return getIdFieldBuilder().addBuilder(
            index, org.multibit.contact.MBHDProtos.Contact.getDefaultInstance());
      }
      public java.util.List<org.multibit.contact.MBHDProtos.Contact.Builder> 
           getIdBuilderList() {
        return getIdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.multibit.contact.MBHDProtos.Contact, org.multibit.contact.MBHDProtos.Contact.Builder, org.multibit.contact.MBHDProtos.ContactOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.multibit.contact.MBHDProtos.Contact, org.multibit.contact.MBHDProtos.Contact.Builder, org.multibit.contact.MBHDProtos.ContactOrBuilder>(
                  id_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:wallet.Contacts)
    }
    
    static {
      defaultInstance = new Contacts(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wallet.Contacts)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_Tag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wallet_Tag_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_Contact_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wallet_Contact_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_Contacts_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wallet_Contacts_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022\006wallet\"\030\n\003Tag\022\021\n\ttag_v" +
      "alue\030\001 \002(\t\"\271\001\n\007Contact\022\n\n\002id\030\001 \002(\t\022\014\n\004na" +
      "me\030\002 \002(\t\022\r\n\005email\030\003 \001(\t\022\022\n\nimage_path\030\004 " +
      "\001(\t\022\027\n\017bitcoin_address\030\005 \001(\t\022\033\n\023extended" +
      "_public_key\030\006 \001(\t\022\r\n\005notes\030\007 \001(\t\022\030\n\003tag\030" +
      "\010 \003(\0132\013.wallet.Tag\022\022\n\nstar_style\030\t \001(\r\"\'" +
      "\n\010Contacts\022\033\n\002id\030\001 \003(\0132\017.wallet.ContactB" +
      "\"\n\024org.multibit.contactB\nMBHDProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_wallet_Tag_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_wallet_Tag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wallet_Tag_descriptor,
              new java.lang.String[] { "TagValue", },
              org.multibit.contact.MBHDProtos.Tag.class,
              org.multibit.contact.MBHDProtos.Tag.Builder.class);
          internal_static_wallet_Contact_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_wallet_Contact_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wallet_Contact_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "ImagePath", "BitcoinAddress", "ExtendedPublicKey", "Notes", "Tag", "StarStyle", },
              org.multibit.contact.MBHDProtos.Contact.class,
              org.multibit.contact.MBHDProtos.Contact.Builder.class);
          internal_static_wallet_Contacts_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_wallet_Contacts_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wallet_Contacts_descriptor,
              new java.lang.String[] { "Id", },
              org.multibit.contact.MBHDProtos.Contacts.class,
              org.multibit.contact.MBHDProtos.Contacts.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
