// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/protobuf/history.proto

package org.multibit.hd.core.protobuf;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

// This class is auto-generated so is exempt from findbugs
@SuppressFBWarnings
public final class MBHDHistoryProtos {
  private MBHDHistoryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HistoryEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     * the unique identifier for the history entry, typically a UUID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     * the unique identifier for the history entry, typically a UUID
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     * the unique identifier for the history entry, typically a UUID
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required int64 created = 2;
    /**
     * <code>required int64 created = 2;</code>
     *
     * <pre>
     * the created datetime in millis since epoch (Unix time)
     * </pre>
     */
    boolean hasCreated();
    /**
     * <code>required int64 created = 2;</code>
     *
     * <pre>
     * the created datetime in millis since epoch (Unix time)
     * </pre>
     */
    long getCreated();

    // required string description = 3;
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * the description of the history entry
     * </pre>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * the description of the history entry
     * </pre>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * the description of the history entry
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // optional string notes = 4;
    /**
     * <code>optional string notes = 4;</code>
     *
     * <pre>
     * notes
     * </pre>
     */
    boolean hasNotes();
    /**
     * <code>optional string notes = 4;</code>
     *
     * <pre>
     * notes
     * </pre>
     */
    java.lang.String getNotes();
    /**
     * <code>optional string notes = 4;</code>
     *
     * <pre>
     * notes
     * </pre>
     */
    com.google.protobuf.ByteString
        getNotesBytes();
  }
  /**
   * Protobuf type {@code HistoryEntry}
   *
   * <pre>
   **
   * A single contact 
   * </pre>
   */
  public static final class HistoryEntry extends
      com.google.protobuf.GeneratedMessage
      implements HistoryEntryOrBuilder {
    // Use HistoryEntry.newBuilder() to construct.
    private HistoryEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HistoryEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HistoryEntry defaultInstance;
    public static HistoryEntry getDefaultInstance() {
      return defaultInstance;
    }

    public HistoryEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HistoryEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              created_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              notes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_HistoryEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_HistoryEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.class, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<HistoryEntry> PARSER =
        new com.google.protobuf.AbstractParser<HistoryEntry>() {
      public HistoryEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HistoryEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HistoryEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     * the unique identifier for the history entry, typically a UUID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     * the unique identifier for the history entry, typically a UUID
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     * the unique identifier for the history entry, typically a UUID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 created = 2;
    public static final int CREATED_FIELD_NUMBER = 2;
    private long created_;
    /**
     * <code>required int64 created = 2;</code>
     *
     * <pre>
     * the created datetime in millis since epoch (Unix time)
     * </pre>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 created = 2;</code>
     *
     * <pre>
     * the created datetime in millis since epoch (Unix time)
     * </pre>
     */
    public long getCreated() {
      return created_;
    }

    // required string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * the description of the history entry
     * </pre>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * the description of the history entry
     * </pre>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * the description of the history entry
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string notes = 4;
    public static final int NOTES_FIELD_NUMBER = 4;
    private java.lang.Object notes_;
    /**
     * <code>optional string notes = 4;</code>
     *
     * <pre>
     * notes
     * </pre>
     */
    public boolean hasNotes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string notes = 4;</code>
     *
     * <pre>
     * notes
     * </pre>
     */
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          notes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string notes = 4;</code>
     *
     * <pre>
     * notes
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      created_ = 0L;
      description_ = "";
      notes_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, created_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNotesBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, created_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNotesBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HistoryEntry}
     *
     * <pre>
     **
     * A single contact 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_HistoryEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_HistoryEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.class, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder.class);
      }

      // Construct using org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        notes_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_HistoryEntry_descriptor;
      }

      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry getDefaultInstanceForType() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.getDefaultInstance();
      }

      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry build() {
        org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry buildPartial() {
        org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry result = new org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.created_ = created_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.notes_ = notes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry) {
          return mergeFrom((org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry other) {
        if (other == org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasNotes()) {
          bitField0_ |= 0x00000008;
          notes_ = other.notes_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCreated()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       * the unique identifier for the history entry, typically a UUID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       * the unique identifier for the history entry, typically a UUID
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       * the unique identifier for the history entry, typically a UUID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       * the unique identifier for the history entry, typically a UUID
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       * the unique identifier for the history entry, typically a UUID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       * the unique identifier for the history entry, typically a UUID
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required int64 created = 2;
      private long created_ ;
      /**
       * <code>required int64 created = 2;</code>
       *
       * <pre>
       * the created datetime in millis since epoch (Unix time)
       * </pre>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 created = 2;</code>
       *
       * <pre>
       * the created datetime in millis since epoch (Unix time)
       * </pre>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required int64 created = 2;</code>
       *
       * <pre>
       * the created datetime in millis since epoch (Unix time)
       * </pre>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000002;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 created = 2;</code>
       *
       * <pre>
       * the created datetime in millis since epoch (Unix time)
       * </pre>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        created_ = 0L;
        onChanged();
        return this;
      }

      // required string description = 3;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * the description of the history entry
       * </pre>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * the description of the history entry
       * </pre>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * the description of the history entry
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * the description of the history entry
       * </pre>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * the description of the history entry
       * </pre>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * the description of the history entry
       * </pre>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      // optional string notes = 4;
      private java.lang.Object notes_ = "";
      /**
       * <code>optional string notes = 4;</code>
       *
       * <pre>
       * notes
       * </pre>
       */
      public boolean hasNotes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string notes = 4;</code>
       *
       * <pre>
       * notes
       * </pre>
       */
      public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string notes = 4;</code>
       *
       * <pre>
       * notes
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string notes = 4;</code>
       *
       * <pre>
       * notes
       * </pre>
       */
      public Builder setNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        notes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string notes = 4;</code>
       *
       * <pre>
       * notes
       * </pre>
       */
      public Builder clearNotes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string notes = 4;</code>
       *
       * <pre>
       * notes
       * </pre>
       */
      public Builder setNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        notes_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HistoryEntry)
    }

    static {
      defaultInstance = new HistoryEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HistoryEntry)
  }

  public interface HistoryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .HistoryEntry historyEntry = 1;
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    java.util.List<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry> 
        getHistoryEntryList();
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry getHistoryEntry(int index);
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    int getHistoryEntryCount();
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    java.util.List<? extends org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder> 
        getHistoryEntryOrBuilderList();
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder getHistoryEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code History}
   *
   * <pre>
   **
   * A collection of history entries
   * </pre>
   */
  public static final class History extends
      com.google.protobuf.GeneratedMessage
      implements HistoryOrBuilder {
    // Use History.newBuilder() to construct.
    private History(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private History(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final History defaultInstance;
    public static History getDefaultInstance() {
      return defaultInstance;
    }

    public History getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private History(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                historyEntry_ = new java.util.ArrayList<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              historyEntry_.add(input.readMessage(org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          historyEntry_ = java.util.Collections.unmodifiableList(historyEntry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_History_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_History_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.class, org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.Builder.class);
    }

    public static com.google.protobuf.Parser<History> PARSER =
        new com.google.protobuf.AbstractParser<History>() {
      public History parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new History(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<History> getParserForType() {
      return PARSER;
    }

    // repeated .HistoryEntry historyEntry = 1;
    public static final int HISTORYENTRY_FIELD_NUMBER = 1;
    private java.util.List<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry> historyEntry_;
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    public java.util.List<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry> getHistoryEntryList() {
      return historyEntry_;
    }
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    public java.util.List<? extends org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder> 
        getHistoryEntryOrBuilderList() {
      return historyEntry_;
    }
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    public int getHistoryEntryCount() {
      return historyEntry_.size();
    }
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry getHistoryEntry(int index) {
      return historyEntry_.get(index);
    }
    /**
     * <code>repeated .HistoryEntry historyEntry = 1;</code>
     *
     * <pre>
     * the history entry, repeated
     * </pre>
     */
    public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder getHistoryEntryOrBuilder(
        int index) {
      return historyEntry_.get(index);
    }

    private void initFields() {
      historyEntry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getHistoryEntryCount(); i++) {
        if (!getHistoryEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < historyEntry_.size(); i++) {
        output.writeMessage(1, historyEntry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < historyEntry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, historyEntry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.multibit.hd.core.protobuf.MBHDHistoryProtos.History prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code History}
     *
     * <pre>
     **
     * A collection of history entries
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_History_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_History_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.class, org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.Builder.class);
      }

      // Construct using org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHistoryEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (historyEntryBuilder_ == null) {
          historyEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          historyEntryBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.internal_static_History_descriptor;
      }

      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.History getDefaultInstanceForType() {
        return org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.getDefaultInstance();
      }

      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.History build() {
        org.multibit.hd.core.protobuf.MBHDHistoryProtos.History result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.History buildPartial() {
        org.multibit.hd.core.protobuf.MBHDHistoryProtos.History result = new org.multibit.hd.core.protobuf.MBHDHistoryProtos.History(this);
        int from_bitField0_ = bitField0_;
        if (historyEntryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            historyEntry_ = java.util.Collections.unmodifiableList(historyEntry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.historyEntry_ = historyEntry_;
        } else {
          result.historyEntry_ = historyEntryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.multibit.hd.core.protobuf.MBHDHistoryProtos.History) {
          return mergeFrom((org.multibit.hd.core.protobuf.MBHDHistoryProtos.History)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.multibit.hd.core.protobuf.MBHDHistoryProtos.History other) {
        if (other == org.multibit.hd.core.protobuf.MBHDHistoryProtos.History.getDefaultInstance()) return this;
        if (historyEntryBuilder_ == null) {
          if (!other.historyEntry_.isEmpty()) {
            if (historyEntry_.isEmpty()) {
              historyEntry_ = other.historyEntry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHistoryEntryIsMutable();
              historyEntry_.addAll(other.historyEntry_);
            }
            onChanged();
          }
        } else {
          if (!other.historyEntry_.isEmpty()) {
            if (historyEntryBuilder_.isEmpty()) {
              historyEntryBuilder_.dispose();
              historyEntryBuilder_ = null;
              historyEntry_ = other.historyEntry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              historyEntryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHistoryEntryFieldBuilder() : null;
            } else {
              historyEntryBuilder_.addAllMessages(other.historyEntry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getHistoryEntryCount(); i++) {
          if (!getHistoryEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.multibit.hd.core.protobuf.MBHDHistoryProtos.History parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.multibit.hd.core.protobuf.MBHDHistoryProtos.History) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .HistoryEntry historyEntry = 1;
      private java.util.List<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry> historyEntry_ =
        java.util.Collections.emptyList();
      private void ensureHistoryEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          historyEntry_ = new java.util.ArrayList<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry>(historyEntry_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder> historyEntryBuilder_;

      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public java.util.List<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry> getHistoryEntryList() {
        if (historyEntryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(historyEntry_);
        } else {
          return historyEntryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public int getHistoryEntryCount() {
        if (historyEntryBuilder_ == null) {
          return historyEntry_.size();
        } else {
          return historyEntryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry getHistoryEntry(int index) {
        if (historyEntryBuilder_ == null) {
          return historyEntry_.get(index);
        } else {
          return historyEntryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder setHistoryEntry(
          int index, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry value) {
        if (historyEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryEntryIsMutable();
          historyEntry_.set(index, value);
          onChanged();
        } else {
          historyEntryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder setHistoryEntry(
          int index, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder builderForValue) {
        if (historyEntryBuilder_ == null) {
          ensureHistoryEntryIsMutable();
          historyEntry_.set(index, builderForValue.build());
          onChanged();
        } else {
          historyEntryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder addHistoryEntry(org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry value) {
        if (historyEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryEntryIsMutable();
          historyEntry_.add(value);
          onChanged();
        } else {
          historyEntryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder addHistoryEntry(
          int index, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry value) {
        if (historyEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryEntryIsMutable();
          historyEntry_.add(index, value);
          onChanged();
        } else {
          historyEntryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder addHistoryEntry(
          org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder builderForValue) {
        if (historyEntryBuilder_ == null) {
          ensureHistoryEntryIsMutable();
          historyEntry_.add(builderForValue.build());
          onChanged();
        } else {
          historyEntryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder addHistoryEntry(
          int index, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder builderForValue) {
        if (historyEntryBuilder_ == null) {
          ensureHistoryEntryIsMutable();
          historyEntry_.add(index, builderForValue.build());
          onChanged();
        } else {
          historyEntryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder addAllHistoryEntry(
          java.lang.Iterable<? extends org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry> values) {
        if (historyEntryBuilder_ == null) {
          ensureHistoryEntryIsMutable();
          super.addAll(values, historyEntry_);
          onChanged();
        } else {
          historyEntryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder clearHistoryEntry() {
        if (historyEntryBuilder_ == null) {
          historyEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          historyEntryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public Builder removeHistoryEntry(int index) {
        if (historyEntryBuilder_ == null) {
          ensureHistoryEntryIsMutable();
          historyEntry_.remove(index);
          onChanged();
        } else {
          historyEntryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder getHistoryEntryBuilder(
          int index) {
        return getHistoryEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder getHistoryEntryOrBuilder(
          int index) {
        if (historyEntryBuilder_ == null) {
          return historyEntry_.get(index);  } else {
          return historyEntryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public java.util.List<? extends org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder> 
           getHistoryEntryOrBuilderList() {
        if (historyEntryBuilder_ != null) {
          return historyEntryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(historyEntry_);
        }
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder addHistoryEntryBuilder() {
        return getHistoryEntryFieldBuilder().addBuilder(
            org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder addHistoryEntryBuilder(
          int index) {
        return getHistoryEntryFieldBuilder().addBuilder(
            index, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .HistoryEntry historyEntry = 1;</code>
       *
       * <pre>
       * the history entry, repeated
       * </pre>
       */
      public java.util.List<org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder> 
           getHistoryEntryBuilderList() {
        return getHistoryEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder> 
          getHistoryEntryFieldBuilder() {
        if (historyEntryBuilder_ == null) {
          historyEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntry.Builder, org.multibit.hd.core.protobuf.MBHDHistoryProtos.HistoryEntryOrBuilder>(
                  historyEntry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          historyEntry_ = null;
        }
        return historyEntryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:History)
    }

    static {
      defaultInstance = new History(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:History)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HistoryEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HistoryEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_History_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_History_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033main/protobuf/history.proto\"O\n\014History" +
      "Entry\022\n\n\002id\030\001 \002(\t\022\017\n\007created\030\002 \002(\003\022\023\n\013de" +
      "scription\030\003 \002(\t\022\r\n\005notes\030\004 \001(\t\".\n\007Histor" +
      "y\022#\n\014historyEntry\030\001 \003(\0132\r.HistoryEntryB2" +
      "\n\035org.multibit.hd.core.protobufB\021MBHDHis" +
      "toryProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HistoryEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HistoryEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HistoryEntry_descriptor,
              new java.lang.String[] { "Id", "Created", "Description", "Notes", });
          internal_static_History_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_History_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_History_descriptor,
              new java.lang.String[] { "HistoryEntry", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
